using System.Collections;
using System.Data;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using Filling_Station_Automated_Workplace.Domain;

namespace Filling_Station_Automated_Workplace.View;

public partial class TanksConfigurator : Window
{
    public TanksConfigurator()
    {
        InitializeComponent();
        var tanksDataTable = Deserialize.GetDataTableFromCsvFile("Tanks.csv");
        TanksConfigurationGrid.ItemsSource = tanksDataTable.DefaultView;
        TanksConfigurationGrid.Columns.Remove(
            TanksConfigurationGrid.Columns.FirstOrDefault(column => column.Header.ToString() == "Id"));
    }

    private void AcceptChangesButton_Click(object sender, RoutedEventArgs e)
    {
        // Get the DataTable from the DataGrid's ItemsSource
        var dataTable = (TanksConfigurationGrid.ItemsSource as DataView)?.Table;

        // Serialize the DataTable to the CSV file
        if (dataTable != null) Serialize.WriteDataTableToCsvWithAutoGeneratedId(dataTable, "Tanks.csv");

        Close();
    }


    private void CancelChangesButton_Click(object sender, RoutedEventArgs e)
    {
        var originalDataTable = Deserialize.GetDataTableFromCsvFile("Tanks.csv");
        TanksConfigurationGrid.ItemsSource = originalDataTable.DefaultView;
        Close();
    }

    private void DeleteRowMenuItem_Click(object sender, RoutedEventArgs e)
    {
        if (TanksConfigurationGrid.SelectedItem != null)
            try
            {
                var selectedItem = TanksConfigurationGrid.SelectedItem;
                var itemsSource = TanksConfigurationGrid.ItemsSource as IList;
                itemsSource?.Remove(selectedItem);
            }
            catch
            {
                MessageBox.Show("Наведите курсор на строку с данными и повторите действие, чтобы удалить её",
                    "Ошибка удаления строки", MessageBoxButton.OK, MessageBoxImage.Error);
            }
    }


    private void DataGrid_PreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
    {
        var dataGrid = (DataGrid)sender;
        if (dataGrid.SelectedCells.Count > 0)
        {
            var selectedRow = dataGrid.SelectedCells[0].Item;
            dataGrid.SelectedItem = selectedRow;
        }
    }
}